### ISSUE TITLE
Google credentials no longer valid

### ISSUE THREAD

**Issue by abvincita** [obzervr/engineer-activity#1]
Hi Observr team,

When running the code I noticed that calls to the backend API (api/taxitrips/***) keeps failing with the following error messages:

`Google.Apis.Auth.OAuth2.Responses.TokenResponseException: Error:"invalid_grant", Description:"Invalid JWT Signature.", Uri:""
   at Google.Apis.Auth.OAuth2.Responses.TokenResponse.FromHttpResponseAsync(HttpResponseMessage response, IClock clock, ILogger logger)
   at Google.Apis.Auth.OAuth2.Requests.TokenRequestExtenstions.ExecuteAsync(TokenRequest request, HttpClient httpClient, String tokenServerUrl, CancellationToken taskCancellationToken, IClock clock, ILogger logger)
   at Google.Apis.Auth.OAuth2.ServiceAccountCredential.RequestAccessTokenAsync(CancellationToken taskCancellationToken)
   at Google.Apis.Auth.OAuth2.TokenRefreshManager.RefreshTokenAsync()
   at Google.Apis.Auth.OAuth2.TokenRefreshManager.ResultWithUnwrappedExceptions[T](Task`1 task)
   at Google.Apis.Auth.OAuth2.TokenRefreshManager.<>c.<GetAccessTokenForRequestAsync>b__10_0(Task`1 task)`

<img width="1083" alt="Screen Shot 2021-05-21 at 1 05 13 pm" src="https://user-images.githubusercontent.com/3397725/119077052-f537b080-ba36-11eb-8c4a-c52560028f81.png">

I researched the error and apparently this happens when the credentials to generate OAuth token are no longer valid. 

I tried using my own service account credentials and it fixed the issue - I am able to generate the OAuth token to call Google's API, however as my account does not have the required permission to obzervr-engineering-tests project, the taxitrips API call is still not working.

Would you be able to generate a new service account key and update the credential file please? Thank you!

Cheers,
Andrea Vincita

**Comment by abvincita** [comment]
I've found a workaround by changing the Google ProjectId to my own project, that way the OAuth token generated by my private key works. 

Still good to fix the credentials in the repo for future candidates though :)

Cheers,
Andrea

**Comment by obzervr** [comment]
Hi Andrea,

Thanks for sending through these details. It's wrong on purpose. The repo is public, so it must not contain valid credentials.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
